#!/bin/bash -e

echo "installing node dependencies..."
npm install

echo "installing bower dependencies..."
bower --config.interactive=false install

echo "building production assets..."
./prodassets

echo "building play application..."
sbt clean dist

