#!/bin/bash -e

echo "installing node dependencies..."
npm install

echo "installing bower dependencies..."
bower --config.interactive=false install

[ -s "$HOME/.rvm/scripts/rvm" ] && source "$HOME/.rvm/scripts/rvm"

echo "building production assets..."
./prodassets

echo "building play application..."
sbt clean stage

