#!/bin/bash -e

echo "copying neo4j_init to wust host"
docker-machine scp -r neo4j_init/ wust:neo4j_init
docker-machine ssh wust sudo rm -rf /neo4j_init
docker-machine ssh wust sudo cp -r neo4j_init/ /neo4j_init

echo "run wust!"
eval $(docker-machine env wust)
docker-compose up
