version: '2'

services:
  wurst:
    image: woost/wust
    ports:
      - "80:9000"
    environment:
      - NEO4J_URL=http://neo4j:7474
      - NEO4J_USER=neo4j
      - NEO4J_PASS=${NEO4J_PASS}
    links:
      - neo4j
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASS}
      - EXTENSION_SCRIPT=/neo4j_init/init.sh
    volumes:
      - data:/data/
      - ./neo4j_init/:/neo4j_init/
volumes:
  data: {}
