version: '2'

services:
  wust:
    image: woost/wust
    ports:
      - "80:9000"
    environment:
      - NEO4J_URL=http://neo4j:7474
      - NEO4J_USER=neo4j
      - NEO4J_PASS=${NEO4J_PASS}
    depends_on:
      - neo4j
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASS}
      - EXTENSION_SCRIPT=/neo4j_init/init.sh
    volumes:
      - /data:/data/
      - /logs:/logs/
      - ./neo4j_init/:/neo4j_init/
  neo4j2s3:
    image: woost/neo4j2s3
    environment:
      - NEO4J_URL=http://neo4j:7474
      - NEO4J_USER=neo4j
      - NEO4J_PASS=${NEO4J_PASS}
      - AWS_ACCESS_KEY_ID=${WUST_AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${WUST_AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${WUST_AWS_DEFAULT_REGION}
