#!/bin/bash -e

NPMPREFIX="$HOME/.node_modules"

echo "export PATH=$NPMPREFIX/bin:$$PATH" >> ~/.bashrc
. ~/.bashrc
mkdir -p $NPMPREFIX
mkdir -p ~/node-install
cd ~/node-install
curl https://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz | tar xz --strip-components=1
./configure --prefix=$NPMPREFIX
make install

echo "prefix = $NPMPREFIX" >> ~/.npmrc
wget --quiet -O - https://www.npmjs.org/install.sh | sh

npm -g install bower broccoli-cli

gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
\curl -sSL https://get.rvm.io | bash -s stable --ruby
[ -s "$HOME/.rvm/scripts/rvm" ] && source "$HOME/.rvm/scripts/rvm"
rvm autolibs disabled
rvm install ruby-2.2.1
gem install compass
