#!/bin/bash -e
GIT_WORK_TREE=../app git checkout -f

export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$PATH:$HOME/.node_modules/bin"

cd ../app
./buildproduction
killall java
sleep 2
killall -9 java
nohup target/universal/stage/bin/wust &

