#!/bin/bash
GIT_WORK_TREE=../app git checkout -f

#TODO: separate start/stop script
#TODO: write PID into file

export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$PATH:$HOME/.node_modules/bin"
source $HOME/export_neo4j_pass

cd ../app
./buildproduction || exit 1

killall java
sleep 2
killall -9 java

target/universal/stage/bin/wust >&- 2>&- &

