#!/bin/bash
GIT_WORK_TREE=../app git checkout -f

#TODO: separate start/stop script
#TODO: write PID into file

export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$PATH:$HOME/.node_modules/bin"
source $HOME/export_neo4j_pass

cd ../app

./buildproduction || exit 1

[ -f target/universal/stage/RUNNING_PID ] && kill $(cat target/universal/stage/RUNNING_PID)

[ -x ../usertest/enable ] && ../usertest/enable >&- 2>&- &

target/universal/stage/bin/wust >&- 2>&- &

