#!/bin/bash -e
neo4j start-no-wait &
echo "building production assets"
./prodassets
echo "building backend"
sbt stage
echo "starting server"
UI_SCRATCHPAD_ENABLED=false target/universal/stage/bin/wust || true
neo4j stop

