#!/bin/bash -e
neo4j-shell -file present.cql

killall unclutter || true
systemctl --user stop redshift || true
killall redshift || true

TMP=$(mktemp -d)
[ "$(hostname)" = "beef" ] && SCALE=1.2 || SCALE=1
chromium --user-data-dir=$TMP --disable-infobars --disable-translate --d --disable-save-password-bubble --no-first-run --no-default-browser-check --high-dpi-support=1 --force-device-scale-factor=$SCALE http://localhost:9000
rm -r $TMP

echo "done"

