#!/bin/bash -e
neo4j-shell -file usertest2.cql
killall unclutter || true
systemctl --user stop redshift || true
killall redshift || true
ffmpeg -y -f alsa -ac 1 -i pulse -f x11grab -r 25 -s `xdpyinfo | grep 'dimensions:'|awk '{print $2}'` -i :0.0 -acodec libvorbis -b:a 128k -c:v libx264 -crf 23 -preset superfast -vsync 1 capture-$(date +"%Y-%m-%d-%H-%M-%S").mkv &
FFMPEGPID=$!

TMP=$(mktemp -d)
[ "$(hostname)" = "beef" ] && SCALE=1.2 || SCALE=1
chromium --user-data-dir=$TMP --disable-infobars --disable-translate --d --disable-save-password-bubble --no-first-run --no-default-browser-check --high-dpi-support=1 --force-device-scale-factor=$SCALE http://localhost:9000/focus/drplTzjjQnKUbLezdznd8w/
rm -r $TMP

kill $FFMPEGPID
sleep 10
